-- V19__offers.sql
-- Config-driven promotions, managed from the admin Offers page. Rotating or pausing
-- an offer of an existing kind is data-only (toggle active / edit fields). Only a
-- brand-new kind needs code. Evaluation lives in PromotionEngine.

CREATE TABLE offers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(50)  NOT NULL UNIQUE,
    kind            VARCHAR(30)  NOT NULL,
    stack_group     VARCHAR(20)  NOT NULL,
    percent         NUMERIC(5,2),
    threshold_amount NUMERIC(10,2),
    gift_label      VARCHAR(200),
    label           VARCHAR(100) NOT NULL,
    priority        INTEGER      NOT NULL DEFAULT 0,
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    starts_at       TIMESTAMP,
    ends_at         TIMESTAMP,
    display_order   INTEGER      NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP    NOT NULL DEFAULT now()
);

-- Launch offers, matching the website Offers section.
INSERT INTO offers (code, kind, stack_group, percent, threshold_amount, gift_label, label, priority, active, display_order) VALUES
    ('launch-20',        'PERCENT_OFF',        'DISCOUNT', 20.00, NULL,   NULL,
        'Launch 20% off', 0, TRUE, 1),
    ('free-delivery-550','FREE_DELIVERY_OVER', 'DELIVERY', NULL,  550.00, NULL,
        'Free delivery over 550', 0, TRUE, 2),
    ('sweet-roll-450',   'FREE_ITEM_OVER',     'GIFT',     NULL,  450.00, 'Complimentary sweet roll (baker''s choice)',
        'Free sweet roll over 450', 0, TRUE, 3);
