-- V22__batch_discounts.sql
-- Dynamic "batch discount": when an item already has enough demand booked for a
-- delivery day, the next customer gets an extra percentage off that item to
-- encourage joining an existing bake batch (fewer distinct doughs = easier days).
--
-- Bands are matched by the item's list price: min inclusive, max exclusive
-- (NULL max = no upper bound). The extra percent is taken off the ALREADY
-- discounted line price (it stacks on top of the launch discount, compounding).
--
-- Tunable/stoppable without a redeploy: edit rows or set active = FALSE. Kill the
-- whole feature instantly with bakery.batch-discount.enabled=false.

CREATE TABLE batch_discount_bands (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label           VARCHAR(100) NOT NULL,
    min_price       NUMERIC(10,2) NOT NULL DEFAULT 0,
    max_price       NUMERIC(10,2),
    threshold_units INTEGER      NOT NULL,
    percent         NUMERIC(5,2) NOT NULL,
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order   INTEGER      NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP    NOT NULL DEFAULT now()
);

-- Launch strategy (price bands, booked-unit trigger, extra %):
--   under 350        -> 4 units -> +5%
--   350 to under 600 -> 2 units -> +4%
--   600 and above    -> 1 unit  -> +4%
INSERT INTO batch_discount_bands (label, min_price, max_price, threshold_units, percent, display_order) VALUES
    ('Batch discount', 0,   350,  4, 5.00, 1),
    ('Batch discount', 350, 600,  2, 4.00, 2),
    ('Batch discount', 600, NULL, 1, 4.00, 3);

-- Persist the batch-discount breakdown on each order for the summary/admin views.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS batch_discount_amount NUMERIC(10,2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS batch_discount_label  VARCHAR(200);
